import '../../products/view_model/product_model.dart';

List<String> momCategoryProductsImages = [
  "https://m.media-amazon.com/images/I/51NvQf4TndL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91wxTqob31L._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/71sOqrd6JHL._SY522_.jpg",
  "https://m.media-amazon.com/images/I/71JqPgwUuIL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71bg5Fu-fLL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71EeTMv8GKL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81vvBvmcmuL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  "https://m.media-amazon.com/images/I/71GrAWYYDyL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61OFT5If6JS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81QbXyUeF5L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  "https://m.media-amazon.com/images/I/51IK2Wyf+JL._SY300_SX300_.jpg",
  "https://m.media-amazon.com/images/I/719uCyytrVL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61TU7H-ve5L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71OVweojn1L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71ZTn2kF-LL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  "https://m.media-amazon.com/images/I/71t3ym7TO-L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81kcCHIebtL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71N0GQZqDVL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/41uMp0IPhxL._AC_.jpg",
  "https://m.media-amazon.com/images/I/71tcVijUM4L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71kmvLrD1mL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Qpu7-BsSL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81ey3kQDmYL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71PTk2u-LzL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81SFE99oxGL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61FP9tXRUPL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71NXamJ3rjL._AC_SY879_.jpg",
  "https://m.media-amazon.com/images/I/61rj1n74esL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/51q8tKpLwyL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/614vBd1APCL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71QQDIATrwL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81ZDQwsQzdL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81bfbN1USPL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81uG9hIQuvL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/9189LzzoehL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Mq0xq6M4L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71w4zYJfifL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91xCqwOqLDL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/813AvjFsclL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81wNBgGmfzL._SX679_PIbundle-16,TopRight,0,0_AA679SH20_.jpg",
  "https://m.media-amazon.com/images/I/71YKgtpLnpL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91s+g1bjrJL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81J0YlRvgAL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81HDV-v1YuL._AC_SY695_.jpg",
];

//List of mom category products
List<ProductModel> momCategoryProductsList = [
  ProductModel(
    productImage: momCategoryProductsImages[0],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[1],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[2],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[3],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[4],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[5],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[6],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[7],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[8],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[9],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[10],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[11],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[12],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[13],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[14],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[15],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[16],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[17],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[18],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
  ProductModel(
    productImage: momCategoryProductsImages[19],
    productName: 'productName',
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: 'https://amzn.to/4fBCFix',
  ),
];
