// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-ggEcxYxOjQhw3wsAUxFasR3xJ93IDs',
    appId: '1:334978897625:web:ae667aeab7cc30e85410c8',
    messagingSenderId: '334978897625',
    projectId: 'e-commerce-750b9',
    authDomain: 'e-commerce-750b9.firebaseapp.com',
    storageBucket: 'e-commerce-750b9.firebasestorage.app',
    measurementId: 'G-KJTR4JL753',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPil_KMU7i6Jtw5iwKI8g6m8K8TKt1MAc',
    appId: '1:334978897625:android:f1a014655ea162855410c8',
    messagingSenderId: '334978897625',
    projectId: 'e-commerce-750b9',
    storageBucket: 'e-commerce-750b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD710uJlIMXDTyKY954qF2tVAljpn6yhVY',
    appId: '1:334978897625:ios:f87dfb96753c03f85410c8',
    messagingSenderId: '334978897625',
    projectId: 'e-commerce-750b9',
    storageBucket: 'e-commerce-750b9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
