import '../products/view_model/product_model.dart';

List<String> cardsCategoryProductsImages = [
  "https://m.media-amazon.com/images/I/81roBNQR5YL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81o139BRs0L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Fbr9O+keL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61YQ8y5w1RL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81j7clXghlL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71YQoFfpS6L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91bcfY8Br1L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/911cWHYMBrL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91smwkRz-zS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/A1eoyOYyA2L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91RlNf8t+aL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/A1WwTsNj4ML._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61YoNJHP1lS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61pDDKhLn-L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81kIcpFfm7L._AC_SX679_.jpg",
];

List<String> cardsCategoryProductsNames = [
  "UK Greetings Son Card",
  "Grandson Reasons Birthday Card",
  "Granddaughter Unique Birthday Card",
  "Hallmark Good Man Son Card",
  "Granddaughter Birthday Card",
  "Grandson Birthday Card",
  "Hallmark New Adventure Card",
  "American Greetings Wishes Card",
  "Papyrus Big Adventure Card",
  "Hallmark Happy You Day Card",
  "Hallmark Classic Car Card",
  "Hallmark Best Birthday Card",
  "Birdie Birthday Card with Stickers",
  "Funny Birthday Card with Stickers",
  "Fireworks Pop Up Cake Card",
];

List<String> cardsCategoryProductsLinks = [
  "https://amzn.to/4fDQNYK",
  "https://amzn.to/4fyEsVK",
  "https://amzn.to/4eDAbz3",
  "https://amzn.to/4fDSwNG",
  "https://amzn.to/4fz2yzV",
  "https://amzn.to/4fBHEQB",
  "https://amzn.to/4987zgf",
  "https://amzn.to/40X8aPP",
  "https://amzn.to/49hvQAN",
  "https://amzn.to/4fEHTKE",
  "https://amzn.to/491T1yL",
  "https://amzn.to/3V0JSk6",
  "https://amzn.to/4905AdL",
  "https://amzn.to/40TJSX3",
  "https://amzn.to/40YJlDg",
];

List<ProductModel> cardsCategoryProductsList = [
ProductModel(
  productImage: cardsCategoryProductsImages[0],
  productName: cardsCategoryProductsNames[0],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[0],
),
ProductModel(
  productImage: cardsCategoryProductsImages[1],
  productName: cardsCategoryProductsNames[1],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[1],
),
ProductModel(
  productImage: cardsCategoryProductsImages[2],
  productName: cardsCategoryProductsNames[2],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[2],
),
ProductModel(
  productImage: cardsCategoryProductsImages[3],
  productName: cardsCategoryProductsNames[3],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[3],
),
ProductModel(
  productImage: cardsCategoryProductsImages[4],
  productName: cardsCategoryProductsNames[4],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[4],
),
ProductModel(
  productImage: cardsCategoryProductsImages[5],
  productName: cardsCategoryProductsNames[5],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[5],
),
ProductModel(
  productImage: cardsCategoryProductsImages[6],
  productName: cardsCategoryProductsNames[6],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[6],
),
ProductModel(
  productImage: cardsCategoryProductsImages[7],
  productName: cardsCategoryProductsNames[7],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[7],
),
ProductModel(
  productImage: cardsCategoryProductsImages[8],
  productName: cardsCategoryProductsNames[8],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[8],
),
ProductModel(
  productImage: cardsCategoryProductsImages[9],
  productName: cardsCategoryProductsNames[9],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[9],
),
ProductModel(
  productImage: cardsCategoryProductsImages[10],
  productName: cardsCategoryProductsNames[10],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[10],
),
ProductModel(
  productImage: cardsCategoryProductsImages[11],
  productName: cardsCategoryProductsNames[11],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[11],
),
ProductModel(
  productImage: cardsCategoryProductsImages[12],
  productName: cardsCategoryProductsNames[12],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[12],
),
ProductModel(
  productImage: cardsCategoryProductsImages[13],
  productName: cardsCategoryProductsNames[13],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[13],
),
ProductModel(
  productImage: cardsCategoryProductsImages[14],
  productName: cardsCategoryProductsNames[14],
  productDescription: 'productDescription',
  productPrice: '15\$',
  productLink: cardsCategoryProductsLinks[14],
),

];
