import '../products/view_model/product_model.dart';

List<String> husbandCategoryProductsImages = [
  "https://m.media-amazon.com/images/I/71qt-a58-GL._SY522_.jpg",
  "https://m.media-amazon.com/images/I/71WoCfLx8HL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81fl5eFs7iL._SY522_.jpg",
  "https://m.media-amazon.com/images/I/710XOV1LpgL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/617KObuU7QL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71oVFlCyAdL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Hy5e7ICaS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Cqp2+rUKL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71e-TabzpNL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71W5zEhqPOL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81+w1j3FzrL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61GS1Bos9xL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61gp+upu7vL._SX522_.jpg",
  "https://m.media-amazon.com/images/I/61UaZeNXGeL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71aOppq8azL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/711feL6v0yL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71v0mkgvfLL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/8132CrtdJzS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71OLHt21zGS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81QVK-+PefL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61LGDGhMEZL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81jaZMD5DVL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81oAbhdOGML._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81C5a4vyFTL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91xchslLylL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81sum4jaSOL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71wa7gkqKJL._SY800_.jpg",
  "https://m.media-amazon.com/images/I/71DHpmEej+L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71BX4Ye6ZTL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/81UkS4DytlL._AC_SY879_.jpg",
  "https://m.media-amazon.com/images/I/71HzGGd7BRL._AC_SX679_.jpg",
];

List<String> husbandCategoryProductsNames = [
  "Knock Knock Love Journal",
  "Bee! Love Card",
  "I Wrote a Book About You",
  "Scratch-Off Date Ideas",
  "WowBefun Birthday Card",
  "BIIB Multitool Pen",
  "Magnetic Flashlight",
  "Jishi Golf Pen Holder",
  "Golf Pen Desktop Game",
  "PRSTENLY Leather Journal",
  "Magnetic Wristband",
  "LED Flashlight Gloves",
  "Screw Extractor Set",
  "Universal Socket Tool",
  "Gaming Socks Nirohee",
  "Dealswin Socks",
  "Gaming Socks Nucinzua",
  "American Greetings Crazy Life Card",
  "TANWIH Wallet Card",
  "American Greetings Romantic Card",
  "WowBefun Funny Card",
  "Hallmark Birthday Card",
  "American Greetings Birthday Card",
  "American Greetings Anniversary Card",
  "Hallmark Anniversary Card",
  "OakiWay Sundial Compass",
  "Engraved Pocket Watch",
  "Happy Anniversary Rock",
  "ONCAI Slippers",
  "Alexander Del Rossa Robe",
  "DAVID ARCHY Robe",
];

List<String> husbandCategoryProductsLinks = [
  "https://amzn.to/3OlmRVw",
  "https://amzn.to/3ZefHZk",
  "https://amzn.to/4g02PvA",
  "https://amzn.to/3CGPNEL",
  "https://amzn.to/4fV4O48",
  "https://amzn.to/40Yzu0i",
  "https://amzn.to/3AHi6lZ",
  "https://amzn.to/3V0Vi7s",
  "https://amzn.to/3OgRFXr",
  "https://amzn.to/48X6yYt",
  "https://amzn.to/3OEB28l",
  "https://amzn.to/4924wpV",
  "https://amzn.to/493Syw8",
  "https://amzn.to/3Ohqc83",
  "https://amzn.to/3Zfqa6Q",
  "https://amzn.to/4ggFeXF",
  "https://amzn.to/4eJcAx5",
  "https://amzn.to/4eFapdF",
  "https://amzn.to/48ZEvaE",
  "https://amzn.to/3B4uU5M",
  "https://amzn.to/3CANq6v",
  "https://amzn.to/493SXi8",
  "https://amzn.to/3V2N9zg",
  "https://amzn.to/3ASM2LN",
  "https://amzn.to/3ATgtl0",
  "https://amzn.to/4fV5XbU",
  "https://amzn.to/3YRRpCQ",
  "https://amzn.to/4hWDZON",
  "https://amzn.to/40YAFwp",
  "https://amzn.to/3CBV3tg",
  "https://amzn.to/4fBWwOU",
];

List<ProductModel> husbandCategoryProductsList = [
  ProductModel(
    productImage: husbandCategoryProductsImages[0],
    productName: husbandCategoryProductsNames[0],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: husbandCategoryProductsLinks[0],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[1],
    productName: husbandCategoryProductsNames[1],
    productDescription: 'productDescription',
    productPrice: '20\$',
    productLink: husbandCategoryProductsLinks[1],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[2],
    productName: husbandCategoryProductsNames[2],
    productDescription: 'productDescription',
    productPrice: '25\$',
    productLink: husbandCategoryProductsLinks[2],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[3],
    productName: husbandCategoryProductsNames[3],
    productDescription: 'productDescription',
    productPrice: '30\$',
    productLink: husbandCategoryProductsLinks[3],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[4],
    productName: husbandCategoryProductsNames[4],
    productDescription: 'productDescription',
    productPrice: '35\$',
    productLink: husbandCategoryProductsLinks[4],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[5],
    productName: husbandCategoryProductsNames[5],
    productDescription: 'productDescription',
    productPrice: '40\$',
    productLink: husbandCategoryProductsLinks[5],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[6],
    productName: husbandCategoryProductsNames[6],
    productDescription: 'productDescription',
    productPrice: '45\$',
    productLink: husbandCategoryProductsLinks[6],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[7],
    productName: husbandCategoryProductsNames[7],
    productDescription: 'productDescription',
    productPrice: '50\$',
    productLink: husbandCategoryProductsLinks[7],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[8],
    productName: husbandCategoryProductsNames[8],
    productDescription: 'productDescription',
    productPrice: '55\$',
    productLink: husbandCategoryProductsLinks[8],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[9],
    productName: husbandCategoryProductsNames[9],
    productDescription: 'productDescription',
    productPrice: '60\$',
    productLink: husbandCategoryProductsLinks[9],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[10],
    productName: husbandCategoryProductsNames[10],
    productDescription: 'productDescription',
    productPrice: '65\$',
    productLink: husbandCategoryProductsLinks[10],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[11],
    productName: husbandCategoryProductsNames[11],
    productDescription: 'productDescription',
    productPrice: '70\$',
    productLink: husbandCategoryProductsLinks[11],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[12],
    productName: husbandCategoryProductsNames[12],
    productDescription: 'productDescription',
    productPrice: '75\$',
    productLink: husbandCategoryProductsLinks[12],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[13],
    productName: husbandCategoryProductsNames[13],
    productDescription: 'productDescription',
    productPrice: '80\$',
    productLink: husbandCategoryProductsLinks[13],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[14],
    productName: husbandCategoryProductsNames[14],
    productDescription: 'productDescription',
    productPrice: '85\$',
    productLink: husbandCategoryProductsLinks[14],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[15],
    productName: husbandCategoryProductsNames[15],
    productDescription: 'productDescription',
    productPrice: '90\$',
    productLink: husbandCategoryProductsLinks[15],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[16],
    productName: husbandCategoryProductsNames[16],
    productDescription: 'productDescription',
    productPrice: '95\$',
    productLink: husbandCategoryProductsLinks[16],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[17],
    productName: husbandCategoryProductsNames[17],
    productDescription: 'productDescription',
    productPrice: '100\$',
    productLink: husbandCategoryProductsLinks[17],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[18],
    productName: husbandCategoryProductsNames[18],
    productDescription: 'productDescription',
    productPrice: '105\$',
    productLink: husbandCategoryProductsLinks[18],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[19],
    productName: husbandCategoryProductsNames[19],
    productDescription: 'productDescription',
    productPrice: '110\$',
    productLink: husbandCategoryProductsLinks[19],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[20],
    productName: husbandCategoryProductsNames[20],
    productDescription: 'productDescription',
    productPrice: '115\$',
    productLink: husbandCategoryProductsLinks[20],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[21],
    productName: husbandCategoryProductsNames[21],
    productDescription: 'productDescription',
    productPrice: '120\$',
    productLink: husbandCategoryProductsLinks[21],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[22],
    productName: husbandCategoryProductsNames[22],
    productDescription: 'productDescription',
    productPrice: '125\$',
    productLink: husbandCategoryProductsLinks[22],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[23],
    productName: husbandCategoryProductsNames[23],
    productDescription: 'productDescription',
    productPrice: '130\$',
    productLink: husbandCategoryProductsLinks[23],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[24],
    productName: husbandCategoryProductsNames[24],
    productDescription: 'productDescription',
    productPrice: '135\$',
    productLink: husbandCategoryProductsLinks[24],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[25],
    productName: husbandCategoryProductsNames[25],
    productDescription: 'productDescription',
    productPrice: '140\$',
    productLink: husbandCategoryProductsLinks[25],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[26],
    productName: husbandCategoryProductsNames[26],
    productDescription: 'productDescription',
    productPrice: '145\$',
    productLink: husbandCategoryProductsLinks[26],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[27],
    productName: husbandCategoryProductsNames[27],
    productDescription: 'productDescription',
    productPrice: '150\$',
    productLink: husbandCategoryProductsLinks[27],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[28],
    productName: husbandCategoryProductsNames[28],
    productDescription: 'productDescription',
    productPrice: '155\$',
    productLink: husbandCategoryProductsLinks[28],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[29],
    productName: husbandCategoryProductsNames[29],
    productDescription: 'productDescription',
    productPrice: '160\$',
    productLink: husbandCategoryProductsLinks[29],
  ),
  ProductModel(
    productImage: husbandCategoryProductsImages[30],
    productName: husbandCategoryProductsNames[30],
    productDescription: 'productDescription',
    productPrice: '165\$',
    productLink: husbandCategoryProductsLinks[30],
  ),
];
