import '../products/view_model/product_model.dart';

List<String> menCategoryProductsImages = [
  "https://m.media-amazon.com/images/I/71qt-a58-GL._SY522_.jpg",
  "https://m.media-amazon.com/images/I/71WoCfLx8HL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81fl5eFs7iL._SY522_.jpg",
  "https://m.media-amazon.com/images/I/710XOV1LpgL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/617KObuU7QL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71oVFlCyAdL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Hy5e7ICaS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Cqp2+rUKL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71e-TabzpNL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71W5zEhqPOL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81+w1j3FzrL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61GS1Bos9xL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61gp+upu7vL._SX522_.jpg",
  "https://m.media-amazon.com/images/I/61UaZeNXGeL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71aOppq8azL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/711feL6v0yL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71v0mkgvfLL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/8132CrtdJzS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71OLHt21zGS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81QVK-+PefL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61LGDGhMEZL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81jaZMD5DVL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81oAbhdOGML._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81C5a4vyFTL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91xchslLylL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81sum4jaSOL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71wa7gkqKJL._SY800_.jpg",
  "https://m.media-amazon.com/images/I/71DHpmEej+L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71BX4Ye6ZTL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/81UkS4DytlL._AC_SY879_.jpg",
  "https://m.media-amazon.com/images/I/71HzGGd7BRL._AC_SX679_.jpg",
];

List<String> menCategoryProductsNames = [
  "Knock Knock Love Journal",
  "Bee! Love Card",
  "I Wrote a Book About You",
  "Scratch-Off Date Ideas",
  "WowBefun Birthday Card",
  "BIIB Multitool Pen",
  "Magnetic Flashlight",
  "Jishi Golf Pen Holder",
  "Golf Pen Desktop Game",
  "PRSTENLY Leather Journal",
  "Magnetic Wristband",
  "LED Flashlight Gloves",
  "Screw Extractor Set",
  "Universal Socket Tool",
  "Gaming Socks Nirohee",
  "Dealswin Socks",
  "Gaming Socks Nucinzua",
  "American Greetings Crazy Life Card",
  "TANWIH Wallet Card",
  "American Greetings Romantic Card",
  "WowBefun Funny Card",
  "Hallmark Birthday Card",
  "American Greetings Birthday Card",
  "American Greetings Anniversary Card",
  "Hallmark Anniversary Card",
  "OakiWay Sundial Compass",
  "Engraved Pocket Watch",
  "Happy Anniversary Rock",
  "ONCAI Slippers",
  "Alexander Del Rossa Robe",
  "DAVID ARCHY Robe",
];

List<String> menCategoryProductsLinks = [
  "https://amzn.to/3OlmRVw",
  "https://amzn.to/3ZefHZk",
  "https://amzn.to/4g02PvA",
  "https://amzn.to/3CGPNEL",
  "https://amzn.to/4fV4O48",
  "https://amzn.to/40Yzu0i",
  "https://amzn.to/3AHi6lZ",
  "https://amzn.to/3V0Vi7s",
  "https://amzn.to/3OgRFXr",
  "https://amzn.to/48X6yYt",
  "https://amzn.to/3OEB28l",
  "https://amzn.to/4924wpV",
  "https://amzn.to/493Syw8",
  "https://amzn.to/3Ohqc83",
  "https://amzn.to/3Zfqa6Q",
  "https://amzn.to/4ggFeXF",
  "https://amzn.to/4eJcAx5",
  "https://amzn.to/4eFapdF",
  "https://amzn.to/48ZEvaE",
  "https://amzn.to/3B4uU5M",
  "https://amzn.to/3CANq6v",
  "https://amzn.to/493SXi8",
  "https://amzn.to/3V2N9zg",
  "https://amzn.to/3ASM2LN",
  "https://amzn.to/3ATgtl0",
  "https://amzn.to/4fV5XbU",
  "https://amzn.to/3YRRpCQ",
  "https://amzn.to/4hWDZON",
  "https://amzn.to/40YAFwp",
  "https://amzn.to/3CBV3tg",
  "https://amzn.to/4fBWwOU",
];

List<ProductModel> husbandCategoryProductsList = [
  ProductModel(
    productImage: menCategoryProductsImages[0],
    productName: menCategoryProductsNames[0],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: menCategoryProductsLinks[0],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[1],
    productName: menCategoryProductsNames[1],
    productDescription: 'productDescription',
    productPrice: '20\$',
    productLink: menCategoryProductsLinks[1],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[2],
    productName: menCategoryProductsNames[2],
    productDescription: 'productDescription',
    productPrice: '25\$',
    productLink: menCategoryProductsLinks[2],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[3],
    productName: menCategoryProductsNames[3],
    productDescription: 'productDescription',
    productPrice: '30\$',
    productLink: menCategoryProductsLinks[3],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[4],
    productName: menCategoryProductsNames[4],
    productDescription: 'productDescription',
    productPrice: '35\$',
    productLink: menCategoryProductsLinks[4],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[5],
    productName: menCategoryProductsNames[5],
    productDescription: 'productDescription',
    productPrice: '40\$',
    productLink: menCategoryProductsLinks[5],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[6],
    productName: menCategoryProductsNames[6],
    productDescription: 'productDescription',
    productPrice: '45\$',
    productLink: menCategoryProductsLinks[6],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[7],
    productName: menCategoryProductsNames[7],
    productDescription: 'productDescription',
    productPrice: '50\$',
    productLink: menCategoryProductsLinks[7],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[8],
    productName: menCategoryProductsNames[8],
    productDescription: 'productDescription',
    productPrice: '55\$',
    productLink: menCategoryProductsLinks[8],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[9],
    productName: menCategoryProductsNames[9],
    productDescription: 'productDescription',
    productPrice: '60\$',
    productLink: menCategoryProductsLinks[9],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[10],
    productName: menCategoryProductsNames[10],
    productDescription: 'productDescription',
    productPrice: '65\$',
    productLink: menCategoryProductsLinks[10],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[11],
    productName: menCategoryProductsNames[11],
    productDescription: 'productDescription',
    productPrice: '70\$',
    productLink: menCategoryProductsLinks[11],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[12],
    productName: menCategoryProductsNames[12],
    productDescription: 'productDescription',
    productPrice: '75\$',
    productLink: menCategoryProductsLinks[12],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[13],
    productName: menCategoryProductsNames[13],
    productDescription: 'productDescription',
    productPrice: '80\$',
    productLink: menCategoryProductsLinks[13],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[14],
    productName: menCategoryProductsNames[14],
    productDescription: 'productDescription',
    productPrice: '85\$',
    productLink: menCategoryProductsLinks[14],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[15],
    productName: menCategoryProductsNames[15],
    productDescription: 'productDescription',
    productPrice: '90\$',
    productLink: menCategoryProductsLinks[15],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[16],
    productName: menCategoryProductsNames[16],
    productDescription: 'productDescription',
    productPrice: '95\$',
    productLink: menCategoryProductsLinks[16],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[17],
    productName: menCategoryProductsNames[17],
    productDescription: 'productDescription',
    productPrice: '100\$',
    productLink: menCategoryProductsLinks[17],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[18],
    productName: menCategoryProductsNames[18],
    productDescription: 'productDescription',
    productPrice: '105\$',
    productLink: menCategoryProductsLinks[18],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[19],
    productName: menCategoryProductsNames[19],
    productDescription: 'productDescription',
    productPrice: '110\$',
    productLink: menCategoryProductsLinks[19],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[20],
    productName: menCategoryProductsNames[20],
    productDescription: 'productDescription',
    productPrice: '115\$',
    productLink: menCategoryProductsLinks[20],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[21],
    productName: menCategoryProductsNames[21],
    productDescription: 'productDescription',
    productPrice: '120\$',
    productLink: menCategoryProductsLinks[21],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[22],
    productName: menCategoryProductsNames[22],
    productDescription: 'productDescription',
    productPrice: '125\$',
    productLink: menCategoryProductsLinks[22],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[23],
    productName: menCategoryProductsNames[23],
    productDescription: 'productDescription',
    productPrice: '130\$',
    productLink: menCategoryProductsLinks[23],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[24],
    productName: menCategoryProductsNames[24],
    productDescription: 'productDescription',
    productPrice: '135\$',
    productLink: menCategoryProductsLinks[24],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[25],
    productName: menCategoryProductsNames[25],
    productDescription: 'productDescription',
    productPrice: '140\$',
    productLink: menCategoryProductsLinks[25],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[26],
    productName: menCategoryProductsNames[26],
    productDescription: 'productDescription',
    productPrice: '145\$',
    productLink: menCategoryProductsLinks[26],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[27],
    productName: menCategoryProductsNames[27],
    productDescription: 'productDescription',
    productPrice: '150\$',
    productLink: menCategoryProductsLinks[27],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[28],
    productName: menCategoryProductsNames[28],
    productDescription: 'productDescription',
    productPrice: '155\$',
    productLink: menCategoryProductsLinks[28],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[29],
    productName: menCategoryProductsNames[29],
    productDescription: 'productDescription',
    productPrice: '160\$',
    productLink: menCategoryProductsLinks[29],
  ),
  ProductModel(
    productImage: menCategoryProductsImages[30],
    productName: menCategoryProductsNames[30],
    productDescription: 'productDescription',
    productPrice: '165\$',
    productLink: menCategoryProductsLinks[30],
  ),
];
