import '../products/view_model/product_model.dart';

List<String> momCategoryProductsImages = [
  "https://m.media-amazon.com/images/I/51NvQf4TndL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91wxTqob31L._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/71sOqrd6JHL._SY522_.jpg",
  "https://m.media-amazon.com/images/I/71JqPgwUuIL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71bg5Fu-fLL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71EeTMv8GKL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81vvBvmcmuL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  "https://m.media-amazon.com/images/I/71GrAWYYDyL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61OFT5If6JS._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81QbXyUeF5L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  "https://m.media-amazon.com/images/I/51IK2Wyf+JL._SY300_SX300_.jpg",
  "https://m.media-amazon.com/images/I/719uCyytrVL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61TU7H-ve5L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71OVweojn1L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71ZTn2kF-LL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  "https://m.media-amazon.com/images/I/71t3ym7TO-L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81kcCHIebtL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71N0GQZqDVL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/41uMp0IPhxL._AC_.jpg",
  "https://m.media-amazon.com/images/I/71tcVijUM4L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71kmvLrD1mL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Qpu7-BsSL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81ey3kQDmYL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71PTk2u-LzL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81SFE99oxGL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61FP9tXRUPL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71NXamJ3rjL._AC_SY879_.jpg",
  "https://m.media-amazon.com/images/I/61rj1n74esL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/51q8tKpLwyL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/614vBd1APCL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71QQDIATrwL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81ZDQwsQzdL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81bfbN1USPL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81uG9hIQuvL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/9189LzzoehL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Mq0xq6M4L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71w4zYJfifL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91xCqwOqLDL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/813AvjFsclL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81wNBgGmfzL._SX679_PIbundle-16,TopRight,0,0_AA679SH20_.jpg",
  "https://m.media-amazon.com/images/I/71YKgtpLnpL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91s+g1bjrJL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81J0YlRvgAL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81HDV-v1YuL._AC_SY695_.jpg"
];

List<String> momCategoryProductsNames = [
  "Amazon Echo Show 5 (Newest Model), Smart Display"
      "Shonyin Dainty Heart-felt Infinity Heart Necklace",
  "KitchenAid Artisan Stand Mixer",
  "Mom, I Want to Hear Your Story: A Mother’s Guided Journal",
  "Crock-Pot 20-Ounce Electric Lunch Box",
  "Tabletop Fire Pit with Smores Maker Kit",
  "Quatish Portable Travel Utensils Set with Case",
  "Klean Kanteen Insulated Water Bottle",
  "3-Bulb Plant Terrarium with Wooden Stand",
  "Eyeris Eye Massager with Heat - Christmas & Birthday Gift for Her, Eye Care & Relaxation",
  "Nesting Grill Baskets (2PCS), Stainless Steel, BBQ Accessories",
  "Smokehouse Grilling Spice Set (20 Flavors)",
  "Bentgo All-in-One Salad Container",
  "Mothers Day Lavender Scented Candle",
  "CHARMDOO Electric Lunch Box",
  "Wildone Mixing Bowls with Airtight Lids (27 Pcs)",
  "AIKKIL Silicone Cooking Utensils Set (43 Pcs)",
  "TRAVELISIMO Electric Lunch Box",
  "Pandasch Engraved Bamboo Cutting Board",
  "Riveira Wooden Spoons for Cooking",
  "U R My Sunshine Music Box",
  "Gifts for Mom Lavender Scented Candle",
  "eos Natural Shea Lip Balm - Birthday Cake",
  "Christmas Rose Flower Glass Dome",
  "Can't Help Falling in Love Music Box",
  "Jumway Not A Day Over Fabulous Mug",
  "Marycele Candle Warmer Lamp",
  "Chesapeake Bay Serenity + Calm Candle",
  "Thymes Frasier Fir Pine Needle Candle",
  "GEEZO Fragrance Candle Warmer Lamp",
  "Fujifilm Instax Mini Link 2 Printer",
  "TEHOOK Fuzzy Socks (Winter)",
  "SpaLife Holiday Facial Masks (12 Pack)",
  "Bath and Body Gift Basket",
  "Scented Candles Gift Set (4 Pack)",
  "BOSECETA Fluffy Pajamas Set",
  "Nacome Solar Garden Turtle Statue",
  "Nacome Solar Cat Outdoor Statue",
  "9 Herb Indoor Garden Kit",
  "Burt's Bees Christmas Gift Set",
  "Popcorn Movie Night Supplies",
  "TOPDesign Utility Tote Bag",
  "ZHMO Canvas Tote Bag",
  "EASYFUN Insulated Lunch Bag",
  "LongBay Chenille Knit Bootie Slippers",
];

List<String> momCategoryProductsLinks = [
  "https://amzn.to/4fNJvkT",
  "https://amzn.to/3CvrWaW",
  "https://amzn.to/3YNSmwg",
  "https://amzn.to/40NmjyQ",
  "https://amzn.to/3UTeUu2",
  "https://amzn.to/4fOwZS9",
  "https://amzn.to/3YQ14Kf",
  "https://amzn.to/48RZFHK",
  "https://amzn.to/4fyq7c8",
  "https://amzn.to/4fqQPmF",
  "https://amzn.to/3Oa5Tt6",
  "https://amzn.to/3AHDqrn",
  "https://amzn.to/48TOVIL",
  "https://amzn.to/3YT7MiA",
  "https://amzn.to/40NGFs3",
  "https://amzn.to/3Oa5WFi",
  "https://amzn.to/4fyLB8z",
  "https://amzn.to/4hRSX8y",
  "https://amzn.to/4fuirr2",
  "https://amzn.to/3Cuizsa",
  "https://amzn.to/40Jw8Ov",
  "https://amzn.to/4i0MVCW",
  "https://amzn.to/40QdlB0",
  "https://amzn.to/3CtH0pD",
  "https://amzn.to/40P348q",
  "https://amzn.to/3Z6kVGl",
  "https://amzn.to/3ZigXuF",
  "https://amzn.to/3Z7Lif8",
  "https://amzn.to/3Z5Lj3i",
  "https://amzn.to/3CuiG74",
  "https://amzn.to/4fF3AtI",
  "https://amzn.to/4hRTcjY",
  "https://amzn.to/48Uiv16",
  "https://amzn.to/3Ctg1KJ",
  "https://amzn.to/40N4akM",
  "https://amzn.to/4hHYI8S",
  "https://amzn.to/48NHanP",
  "https://amzn.to/4fqRN2h",
  "https://amzn.to/48NH9Ah",
  "https://amzn.to/4hOF2QG",
  "https://amzn.to/4fuiMdi",
  "https://amzn.to/4fK4HrY",
  "https://amzn.to/4hMZCRA",
  "https://amzn.to/4hM4tm3",
];
//List of mom category products
List<ProductModel> momCategoryProductsList = [
  ProductModel(
    productImage: momCategoryProductsImages[0],
    productName: momCategoryProductsNames[0],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[0],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[1],
    productName: momCategoryProductsNames[1],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[1],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[2],
    productName: momCategoryProductsNames[2],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[2],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[3],
    productName: momCategoryProductsNames[3],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[3],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[4],
    productName: momCategoryProductsNames[4],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[4],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[5],
    productName: momCategoryProductsNames[5],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[5],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[6],
    productName: momCategoryProductsNames[6],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[6],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[7],
    productName: momCategoryProductsNames[7],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[7],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[8],
    productName: momCategoryProductsNames[8],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[8],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[9],
    productName: momCategoryProductsNames[9],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[9],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[10],
    productName: momCategoryProductsNames[10],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[10],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[11],
    productName: momCategoryProductsNames[11],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[11],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[12],
    productName: momCategoryProductsNames[12],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[12],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[13],
    productName: momCategoryProductsNames[13],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[13],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[14],
    productName: momCategoryProductsNames[14],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[14],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[15],
    productName: momCategoryProductsNames[15],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[15],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[16],
    productName: momCategoryProductsNames[16],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[16],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[17],
    productName: momCategoryProductsNames[17],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[17],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[18],
    productName: momCategoryProductsNames[18],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[18],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[19],
    productName: momCategoryProductsNames[19],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[19],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[20],
    productName: momCategoryProductsNames[20],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[20],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[21],
    productName: momCategoryProductsNames[21],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[21],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[22],
    productName: momCategoryProductsNames[22],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[22],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[23],
    productName: momCategoryProductsNames[23],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[23],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[24],
    productName: momCategoryProductsNames[24],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[24],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[25],
    productName: momCategoryProductsNames[25],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[25],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[26],
    productName: momCategoryProductsNames[26],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[26],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[27],
    productName: momCategoryProductsNames[27],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[27],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[28],
    productName: momCategoryProductsNames[28],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[28],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[29],
    productName: momCategoryProductsNames[29],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[29],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[30],
    productName: momCategoryProductsNames[30],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[30],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[31],
    productName: momCategoryProductsNames[31],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[31],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[32],
    productName: momCategoryProductsNames[32],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[32],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[33],
    productName: momCategoryProductsNames[33],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[33],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[34],
    productName: momCategoryProductsNames[34],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[34],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[35],
    productName: momCategoryProductsNames[35],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[35],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[36],
    productName: momCategoryProductsNames[36],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[36],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[37],
    productName: momCategoryProductsNames[37],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[37],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[38],
    productName: momCategoryProductsNames[38],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[38],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[39],
    productName: momCategoryProductsNames[39],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[39],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[40],
    productName: momCategoryProductsNames[40],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[40],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[41],
    productName: momCategoryProductsNames[41],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[41],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[42],
    productName: momCategoryProductsNames[42],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[42],
  ),
  ProductModel(
    productImage: momCategoryProductsImages[43],
    productName: momCategoryProductsNames[43],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: momCategoryProductsLinks[43],
  ),
];
