import '../products/view_model/product_model.dart';

List<String> womenCategoryProductsImages = [
  "https://m.media-amazon.com/images/I/81JuXVcBcjL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81sYYMdoRLL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81R8+RzwINL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Jnd9ccAdL._AC_SX679_PIbundle-16,TopRight,0,0_SH20_.jpg",
  "https://m.media-amazon.com/images/I/71oVpy6qf3L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61YFsLeZgOL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71bg5Fu-fLL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71NqhmVGCIL._SX679_PIbundle-8,TopRight,0,0_AA679SH20_.jpg",
  "https://m.media-amazon.com/images/I/81lszWlkGGL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61fL4gU4-nL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/712zvtu7nyL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91E+Eoshf1L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91UbPqgGcTL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91xCqwOqLDL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71GrAWYYDyL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/813AvjFsclL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/814po+xzHvL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/816yKrf06qL._AC_SX679_PIbundle-12,TopRight,0,0_SH20_.jpg",
  "https://m.media-amazon.com/images/I/81+CZPubNNL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/51sdlEpzVBL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71+Bsd84XsL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/713rEZJa92L._SX679_.jpg",
  "https://m.media-amazon.com/images/I/71AEbODrs9L._SX679_.jpg",
  "https://m.media-amazon.com/images/I/41bSTVExrAL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/51dSKjL6BxL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61mIEUEYWdL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61eVeJIouwL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61jLiF5IVKL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/51SEFSyG4oL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/41MtTDLtHKL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61L7j5eLLIL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61a3ooePTJL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/614YytHDzPL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/71us40-DZaL._AC_SX695_.jpg",
  "https://m.media-amazon.com/images/I/71IlOiLSMJL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61HuqZJkSqL._AC_SY879_.jpg",
  "https://m.media-amazon.com/images/I/51YygNHI68L._AC_SY879_.jpg",
  "https://m.media-amazon.com/images/I/51nhXAtNA1L._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61riAesTTNL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61eLFmhyr1L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71fnIod1SqL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/51E76z7oaWL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/718nl7gQL5L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/51vO6NWLj7L._SX679_.jpg",
  "https://m.media-amazon.com/images/I/914FIdPsvML._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71QDsaFZF9L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/519gUuEd2GL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/711Z9Ju3AqL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/41Ai-GLQzQL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  "https://m.media-amazon.com/images/I/714-hJx2WbL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/71UOLM5B38L._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81g08dnS6hL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/718tQqoGyYL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/81bfbN1USPL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/61olJClLFoL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81d6j+2pqlL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91dSs7Lcs4L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91YMzTQg1sL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/91QIykOXykL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61yMq+Ez+bL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71V9RCIBssL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/61bAqal3ENL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/71JfYBeUjpL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81+YmLDehkL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61dsmF8lkTL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71PTk2u-LzL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61mYSYWjtrL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61xnfiYbw0L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/617jWhurG3L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71Mq0xq6M4L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/61zIwoNjoNL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/71H0hEwZY-L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71yyQEGylML._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81HGpJbrnaL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81YS7014JPL._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/8142dAEim3L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/71pb+JOaCHL._SX679_.jpg",
  "https://m.media-amazon.com/images/I/516tnauVb+L._AC_SX679_.jpg",
  "https://m.media-amazon.com/images/I/81nV5EZvAqL._AC_SY695_.jpg",
  "https://m.media-amazon.com/images/I/61vyXDZovzL._AC_SY695_.jpg"
];

List<String> womenCategoryProductsNames = [
  "Gel Nail Polish Kit",
  "Luggage Organizer Bags Set",
  "Packing Cubes with Toiletry Bag",
  "Travel Bottles Set",
  "Packing Cubes for Travel",
  "Packing Cubes Luggage Organizers",
  "Tabletop Fire Pit with Smores Kit",
  "Popcorn Kernels and Seasoning Variety Pack",
  "Chocolate Fondue Kit",
  "Badass Affirmation Cards",
  "Friendship Ceramic Ring Dish",
  "Birthday Gifts Basket for Women",
  "Luxury Bath & Body Set",
  "Herb Indoor Window Garden Kit",
  "Plant Terrarium with Wooden Stand",
  "Burt's Bees Christmas Gifts",
  "Bonsai Starter Kit",
  "Scented Candles Gift Set",
  "Shea Sugar Scrub Coco Colada",
  "Makeup Mirror Vanity Mirror",
  "Rotating Makeup Organizer",
  "Makeup Brushes Set",
  "Makeup Brush Set",
  "Soft Pinch Matte Liquid Blush",
  "Elisa Pendant Necklace",
  "Elaina Adjustable Chain Bracelet",
  "Lee Drop Earrings",
  "Nola Stud Earrings",
  "Freshwater Pearl Pendant Necklace",
  "Tahitian Black Pearl Necklace",
  "Gold Earrings",
  "Steve Madden Breslin Sandal",
  "Calvin Klein Tegin Sandal",
  "Steve Madden Theresa Sandal",
  "Jessica Simpson Phindies Pump",
  "Memoriesea Maxi Dress",
  "WOOSEA Mermaid Dress",
  "Fashare Stiletto Pumps",
  "Jessica Simpson Rayli Sandals",
  "Caratize Diamond Pendant",
  "Litfun Slippers",
  "JISULIFE Handheld Mini Fan",
  "CAOODKDK Electronic Organizer",
  "Kintion Pocket Mirror",
  "Anne Klein Crystal Bangle Watch Set",
  "Anne Klein Diamond Dial Bangle Watch",
  "THE COMFY Wearable Blanket",
  "TEHOOK Fuzzy Socks",
  "Chantomoo Memory Foam Slippers",
  "Stanley IceFlow Tumbler",
  "grace & stella Under Eye Mask",
  "Permotary Collagen Lip Mask",
  "Nekteck Shiatsu Foot Massager",
  "Birthday Spa Gift Basket",
  "BEDELITE Satin Pillowcase",
  "5 Pack Wool Socks",
  "LifeAround2Angels Bath Bombs",
  "EBMORE Merino Wool Socks",
  "Cleverfy Shower Steamers Aromatherapy",
  "Comfytemp Weighted Heating Pad",
  "BAIMEI Gua Sha & Jade Roller Set (Green)",
  "BAIMEI Jade Roller & Gua Sha (Pink)",
  "RENPHO Heating Pad for Back Pain Relief",
  "Willow Tree Friendship Keepsake Box",
  "Lavender Scented Candles Gifts for Women",
  "Can't Help Falling in Love Music Box",
  "KECHO 14k Yellow Gold Honey Bee Pendant",
  "TheraICE Headache Relief Cap",
  "Bedsure White Throw Blanket",
  "Nacome Solar Garden Turtle Statue",
  "Kate Spade New York Sparkle Round Earrings",
  "KElofoN Travel Jewelry Case with Mirror",
  "KElofoN Travel Jewelry Organizer",
  "LANDNEOO Vintage Coffee Mugs Set",
  "NETANY Drinking Glasses with Bamboo Lids",
  "SMIRLY Charcuterie Boards Gift Set",
  "Body Restore Shower Steamers",
  "INIU Portable Charger",
  "NanoStyle I Love You Necklace",
  "1/6 to 1 Carat Diamond Circle of Life Pendant",
];

List<String> womenCategoryProductsLinks = [
  "https://amzn.to/3CLfB2m",
  "https://amzn.to/3ZiMxsc",
  "https://amzn.to/3CxEBdE",
  "https://amzn.to/3OfJL0a",
  "https://amzn.to/3APXuYC",
  "https://amzn.to/3ZiMJYs",
  "https://amzn.to/3UW87A8",
  "https://amzn.to/3AM7wdp",
  "https://amzn.to/3Ofjork",
  "https://amzn.to/4fywDPP",
  "https://amzn.to/3Of7IF9",
  "https://amzn.to/3OiCGfy",
  "https://amzn.to/3CyPrjB",
  "https://amzn.to/40WYrZY",
  "https://amzn.to/40VjDQ3",
  "https://amzn.to/4hWUavu",
  "https://amzn.to/4eFYUmz",
  "https://amzn.to/3ZhU22x",
  "https://amzn.to/48W4PCF",
  "https://amzn.to/3ATGb95",
  "https://amzn.to/3Zdc3yR",
  "https://amzn.to/3ZfAVWI",
  "https://amzn.to/3ARGeCs",
  "https://amzn.to/4fRFE6m",
  "https://amzn.to/3ZepTRq",
  "https://amzn.to/3CN2VrN",
  "https://amzn.to/4fVJbAu",
  "https://amzn.to/3ZblE9j",
  "https://amzn.to/3Zfp8HU",
  "https://amzn.to/4fWfzmF",
  "https://amzn.to/3CzTyvE",
  "https://amzn.to/4fyofjy",
  "https://amzn.to/4eA1J8p",
  "https://amzn.to/4hZASFE",
  "https://amzn.to/3CBSjMy",
  "https://amzn.to/4fAgd9Q",
  "https://amzn.to/4hVoMxw",
  "https://amzn.to/3ANww3W",
  "https://amzn.to/3UYx0uI",
  "https://amzn.to/491b4Vz",
  "https://amzn.to/3Z0LTOo",
  "https://amzn.to/3CAl3Fz",
  "https://amzn.to/4eCjvIf",
  "https://amzn.to/3YYTZad",
  "https://amzn.to/3CFDGrG",
  "https://amzn.to/4fS8548",
  "https://amzn.to/491bgEh",
  "https://amzn.to/3V2s7AV",
  "https://amzn.to/3V2MU7p",
  "https://amzn.to/49fIuAh",
  "https://amzn.to/3CxGAP8",
  "https://amzn.to/3ZcNm5w",
  "https://amzn.to/4eG1nNR",
  "https://amzn.to/3V4bZPp",
  "https://amzn.to/4fC6b7Y",
  "https://amzn.to/4fC9igd",
  "https://amzn.to/4hWdGYW",
  "https://amzn.to/4hUFblM",
  "https://amzn.to/3AQsiII",
  "https://amzn.to/3Z01cag",
  "https://amzn.to/3YXF2Ft",
  "https://amzn.to/3UYEuOx",
  "https://amzn.to/4fAjeaa",
  "https://amzn.to/3YPUmnq",
  "https://amzn.to/491vzS3",
  "https://amzn.to/3ANzvJG",
  "https://amzn.to/3ANzk0Y",
  "https://amzn.to/3B2AXYy",
  "https://amzn.to/3AD8xVa",
  "https://amzn.to/4fY9ciD",
  "https://amzn.to/3OoFEip",
  "https://amzn.to/3ATjvFX",
  "https://amzn.to/4fZeoDf",
  "https://amzn.to/3CAZrZr",
  "https://amzn.to/4fAr0AO",
  "https://amzn.to/40Xs2m4",
  "https://amzn.to/3Zj0qp5",
  "https://amzn.to/3ARa2is",
  "https://amzn.to/3V08GZC",
  "https://amzn.to/3OjVBGO",
];

List<ProductModel> womenCategoryProductsList = [
  ProductModel(
    productImage: womenCategoryProductsImages[0],
    productName: womenCategoryProductsNames[0],
    productDescription: 'productDescription',
    productPrice: '15\$',
    productLink: womenCategoryProductsLinks[0],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[1],
    productName: womenCategoryProductsNames[1],
    productDescription: 'productDescription',
    productPrice: '20\$',
    productLink: womenCategoryProductsLinks[1],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[2],
    productName: womenCategoryProductsNames[2],
    productDescription: 'productDescription',
    productPrice: '25\$',
    productLink: womenCategoryProductsLinks[2],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[3],
    productName: womenCategoryProductsNames[3],
    productDescription: 'productDescription',
    productPrice: '30\$',
    productLink: womenCategoryProductsLinks[3],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[4],
    productName: womenCategoryProductsNames[4],
    productDescription: 'productDescription',
    productPrice: '35\$',
    productLink: womenCategoryProductsLinks[4],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[5],
    productName: womenCategoryProductsNames[5],
    productDescription: 'productDescription',
    productPrice: '40\$',
    productLink: womenCategoryProductsLinks[5],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[6],
    productName: womenCategoryProductsNames[6],
    productDescription: 'productDescription',
    productPrice: '45\$',
    productLink: womenCategoryProductsLinks[6],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[7],
    productName: womenCategoryProductsNames[7],
    productDescription: 'productDescription',
    productPrice: '50\$',
    productLink: womenCategoryProductsLinks[7],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[8],
    productName: womenCategoryProductsNames[8],
    productDescription: 'productDescription',
    productPrice: '55\$',
    productLink: womenCategoryProductsLinks[8],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[9],
    productName: womenCategoryProductsNames[9],
    productDescription: 'productDescription',
    productPrice: '60\$',
    productLink: womenCategoryProductsLinks[9],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[10],
    productName: womenCategoryProductsNames[10],
    productDescription: 'productDescription',
    productPrice: '65\$',
    productLink: womenCategoryProductsLinks[10],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[11],
    productName: womenCategoryProductsNames[11],
    productDescription: 'productDescription',
    productPrice: '70\$',
    productLink: womenCategoryProductsLinks[11],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[12],
    productName: womenCategoryProductsNames[12],
    productDescription: 'productDescription',
    productPrice: '75\$',
    productLink: womenCategoryProductsLinks[12],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[13],
    productName: womenCategoryProductsNames[13],
    productDescription: 'productDescription',
    productPrice: '80\$',
    productLink: womenCategoryProductsLinks[13],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[14],
    productName: womenCategoryProductsNames[14],
    productDescription: 'productDescription',
    productPrice: '85\$',
    productLink: womenCategoryProductsLinks[14],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[15],
    productName: womenCategoryProductsNames[15],
    productDescription: 'productDescription',
    productPrice: '90\$',
    productLink: womenCategoryProductsLinks[15],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[16],
    productName: womenCategoryProductsNames[16],
    productDescription: 'productDescription',
    productPrice: '95\$',
    productLink: womenCategoryProductsLinks[16],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[17],
    productName: womenCategoryProductsNames[17],
    productDescription: 'productDescription',
    productPrice: '100\$',
    productLink: womenCategoryProductsLinks[17],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[18],
    productName: womenCategoryProductsNames[18],
    productDescription: 'productDescription',
    productPrice: '105\$',
    productLink: womenCategoryProductsLinks[18],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[19],
    productName: womenCategoryProductsNames[19],
    productDescription: 'productDescription',
    productPrice: '110\$',
    productLink: womenCategoryProductsLinks[19],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[20],
    productName: womenCategoryProductsNames[20],
    productDescription: 'productDescription',
    productPrice: '115\$',
    productLink: womenCategoryProductsLinks[20],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[21],
    productName: womenCategoryProductsNames[21],
    productDescription: 'productDescription',
    productPrice: '120\$',
    productLink: womenCategoryProductsLinks[21],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[22],
    productName: womenCategoryProductsNames[22],
    productDescription: 'productDescription',
    productPrice: '125\$',
    productLink: womenCategoryProductsLinks[22],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[23],
    productName: womenCategoryProductsNames[23],
    productDescription: 'productDescription',
    productPrice: '130\$',
    productLink: womenCategoryProductsLinks[23],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[24],
    productName: womenCategoryProductsNames[24],
    productDescription: 'productDescription',
    productPrice: '135\$',
    productLink: womenCategoryProductsLinks[24],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[25],
    productName: womenCategoryProductsNames[25],
    productDescription: 'productDescription',
    productPrice: '140\$',
    productLink: womenCategoryProductsLinks[25],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[26],
    productName: womenCategoryProductsNames[26],
    productDescription: 'productDescription',
    productPrice: '145\$',
    productLink: womenCategoryProductsLinks[26],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[27],
    productName: womenCategoryProductsNames[27],
    productDescription: 'productDescription',
    productPrice: '150\$',
    productLink: womenCategoryProductsLinks[27],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[28],
    productName: womenCategoryProductsNames[28],
    productDescription: 'productDescription',
    productPrice: '155\$',
    productLink: womenCategoryProductsLinks[28],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[29],
    productName: womenCategoryProductsNames[29],
    productDescription: 'productDescription',
    productPrice: '160\$',
    productLink: womenCategoryProductsLinks[29],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[30],
    productName: womenCategoryProductsNames[30],
    productDescription: 'productDescription',
    productPrice: '165\$',
    productLink: womenCategoryProductsLinks[30],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[31],
    productName: womenCategoryProductsNames[31],
    productDescription: 'productDescription',
    productPrice: '170\$',
    productLink: womenCategoryProductsLinks[31],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[32],
    productName: womenCategoryProductsNames[32],
    productDescription: 'productDescription',
    productPrice: '175\$',
    productLink: womenCategoryProductsLinks[32],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[33],
    productName: womenCategoryProductsNames[33],
    productDescription: 'productDescription',
    productPrice: '180\$',
    productLink: womenCategoryProductsLinks[33],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[34],
    productName: womenCategoryProductsNames[34],
    productDescription: 'productDescription',
    productPrice: '185\$',
    productLink: womenCategoryProductsLinks[34],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[35],
    productName: womenCategoryProductsNames[35],
    productDescription: 'productDescription',
    productPrice: '190\$',
    productLink: womenCategoryProductsLinks[35],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[36],
    productName: womenCategoryProductsNames[36],
    productDescription: 'productDescription',
    productPrice: '195\$',
    productLink: womenCategoryProductsLinks[36],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[37],
    productName: womenCategoryProductsNames[37],
    productDescription: 'productDescription',
    productPrice: '200\$',
    productLink: womenCategoryProductsLinks[37],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[38],
    productName: womenCategoryProductsNames[38],
    productDescription: 'productDescription',
    productPrice: '205\$',
    productLink: womenCategoryProductsLinks[38],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[39],
    productName: womenCategoryProductsNames[39],
    productDescription: 'productDescription',
    productPrice: '210\$',
    productLink: womenCategoryProductsLinks[39],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[40],
    productName: womenCategoryProductsNames[40],
    productDescription: 'productDescription',
    productPrice: '215\$',
    productLink: womenCategoryProductsLinks[40],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[41],
    productName: womenCategoryProductsNames[41],
    productDescription: 'productDescription',
    productPrice: '220\$',
    productLink: womenCategoryProductsLinks[41],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[42],
    productName: womenCategoryProductsNames[42],
    productDescription: 'productDescription',
    productPrice: '225\$',
    productLink: womenCategoryProductsLinks[42],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[43],
    productName: womenCategoryProductsNames[43],
    productDescription: 'productDescription',
    productPrice: '230\$',
    productLink: womenCategoryProductsLinks[43],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[44],
    productName: womenCategoryProductsNames[44],
    productDescription: 'productDescription',
    productPrice: '235\$',
    productLink: womenCategoryProductsLinks[44],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[45],
    productName: womenCategoryProductsNames[45],
    productDescription: 'productDescription',
    productPrice: '240\$',
    productLink: womenCategoryProductsLinks[45],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[46],
    productName: womenCategoryProductsNames[46],
    productDescription: 'productDescription',
    productPrice: '245\$',
    productLink: womenCategoryProductsLinks[46],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[47],
    productName: womenCategoryProductsNames[47],
    productDescription: 'productDescription',
    productPrice: '250\$',
    productLink: womenCategoryProductsLinks[47],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[48],
    productName: womenCategoryProductsNames[48],
    productDescription: 'productDescription',
    productPrice: '255\$',
    productLink: womenCategoryProductsLinks[48],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[49],
    productName: womenCategoryProductsNames[49],
    productDescription: 'productDescription',
    productPrice: '260\$',
    productLink: womenCategoryProductsLinks[49],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[50],
    productName: womenCategoryProductsNames[50],
    productDescription: 'productDescription',
    productPrice: '265\$',
    productLink: womenCategoryProductsLinks[50],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[51],
    productName: womenCategoryProductsNames[51],
    productDescription: 'productDescription',
    productPrice: '270\$',
    productLink: womenCategoryProductsLinks[51],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[52],
    productName: womenCategoryProductsNames[52],
    productDescription: 'productDescription',
    productPrice: '275\$',
    productLink: womenCategoryProductsLinks[52],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[53],
    productName: womenCategoryProductsNames[53],
    productDescription: 'productDescription',
    productPrice: '280\$',
    productLink: womenCategoryProductsLinks[53],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[54],
    productName: womenCategoryProductsNames[54],
    productDescription: 'productDescription',
    productPrice: '285\$',
    productLink: womenCategoryProductsLinks[54],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[55],
    productName: womenCategoryProductsNames[55],
    productDescription: 'productDescription',
    productPrice: '290\$',
    productLink: womenCategoryProductsLinks[55],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[56],
    productName: womenCategoryProductsNames[56],
    productDescription: 'productDescription',
    productPrice: '295\$',
    productLink: womenCategoryProductsLinks[56],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[57],
    productName: womenCategoryProductsNames[57],
    productDescription: 'productDescription',
    productPrice: '300\$',
    productLink: womenCategoryProductsLinks[57],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[58],
    productName: womenCategoryProductsNames[58],
    productDescription: 'productDescription',
    productPrice: '305\$',
    productLink: womenCategoryProductsLinks[58],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[59],
    productName: womenCategoryProductsNames[59],
    productDescription: 'productDescription',
    productPrice: '310\$',
    productLink: womenCategoryProductsLinks[59],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[60],
    productName: womenCategoryProductsNames[60],
    productDescription: 'productDescription',
    productPrice: '315\$',
    productLink: womenCategoryProductsLinks[60],
  ),
  ProductModel(
    productImage: womenCategoryProductsImages[61],
    productName: womenCategoryProductsNames[61],
    productDescription: 'productDescription',
    productPrice: '320\$',
    productLink: womenCategoryProductsLinks[61],
  ),
ProductModel(
  productImage: womenCategoryProductsImages[62],
  productName: womenCategoryProductsNames[62],
  productDescription: 'productDescription',
  productPrice: '325\$',
  productLink: womenCategoryProductsLinks[62],
),
ProductModel(
  productImage: womenCategoryProductsImages[63],
  productName: womenCategoryProductsNames[63],
  productDescription: 'productDescription',
  productPrice: '330\$',
  productLink: womenCategoryProductsLinks[63],
),
ProductModel(
  productImage: womenCategoryProductsImages[64],
  productName: womenCategoryProductsNames[64],
  productDescription: 'productDescription',
  productPrice: '335\$',
  productLink: womenCategoryProductsLinks[64],
),
ProductModel(
  productImage: womenCategoryProductsImages[65],
  productName: womenCategoryProductsNames[65],
  productDescription: 'productDescription',
  productPrice: '340\$',
  productLink: womenCategoryProductsLinks[65],
),
ProductModel(
  productImage: womenCategoryProductsImages[66],
  productName: womenCategoryProductsNames[66],
  productDescription: 'productDescription',
  productPrice: '345\$',
  productLink: womenCategoryProductsLinks[66],
),
ProductModel(
  productImage: womenCategoryProductsImages[67],
  productName: womenCategoryProductsNames[67],
  productDescription: 'productDescription',
  productPrice: '350\$',
  productLink: womenCategoryProductsLinks[67],
),
ProductModel(
  productImage: womenCategoryProductsImages[68],
  productName: womenCategoryProductsNames[68],
  productDescription: 'productDescription',
  productPrice: '355\$',
  productLink: womenCategoryProductsLinks[68],
),
ProductModel(
  productImage: womenCategoryProductsImages[69],
  productName: womenCategoryProductsNames[69],
  productDescription: 'productDescription',
  productPrice: '360\$',
  productLink: womenCategoryProductsLinks[69],
),
ProductModel(
  productImage: womenCategoryProductsImages[70],
  productName: womenCategoryProductsNames[70],
  productDescription: 'productDescription',
  productPrice: '365\$',
  productLink: womenCategoryProductsLinks[70],
),
ProductModel(
  productImage: womenCategoryProductsImages[71],
  productName: womenCategoryProductsNames[71],
  productDescription: 'productDescription',
  productPrice: '370\$',
  productLink: womenCategoryProductsLinks[71],
),
ProductModel(
  productImage: womenCategoryProductsImages[72],
  productName: womenCategoryProductsNames[72],
  productDescription: 'productDescription',
  productPrice: '375\$',
  productLink: womenCategoryProductsLinks[72],
),
ProductModel(
  productImage: womenCategoryProductsImages[73],
  productName: womenCategoryProductsNames[73],
  productDescription: 'productDescription',
  productPrice: '380\$',
  productLink: womenCategoryProductsLinks[73],
),
ProductModel(
  productImage: womenCategoryProductsImages[74],
  productName: womenCategoryProductsNames[74],
  productDescription: 'productDescription',
  productPrice: '385\$',
  productLink: womenCategoryProductsLinks[74],
),
ProductModel(
  productImage: womenCategoryProductsImages[75],
  productName: womenCategoryProductsNames[75],
  productDescription: 'productDescription',
  productPrice: '390\$',
  productLink: womenCategoryProductsLinks[75],
),
ProductModel(
  productImage: womenCategoryProductsImages[76],
  productName: womenCategoryProductsNames[76],
  productDescription: 'productDescription',
  productPrice: '395\$',
  productLink: womenCategoryProductsLinks[76],
),
ProductModel(
  productImage: womenCategoryProductsImages[77],
  productName: womenCategoryProductsNames[77],
  productDescription: 'productDescription',
  productPrice: '400\$',
  productLink: womenCategoryProductsLinks[77],
),
ProductModel(
  productImage: womenCategoryProductsImages[78],
  productName: womenCategoryProductsNames[78],
  productDescription: 'productDescription',
  productPrice: '405\$',
  productLink: womenCategoryProductsLinks[78],
),
ProductModel(
  productImage: womenCategoryProductsImages[79],
  productName: womenCategoryProductsNames[79],
  productDescription: 'productDescription',
  productPrice: '410\$',
  productLink: womenCategoryProductsLinks[79],
),
// ProductModel(
//   productImage: womenCategoryProductsImages[80],
//   productName: womenCategoryProductsNames[80],
//   productDescription: 'productDescription',
//   productPrice: '410\$',
//   productLink: womenCategoryProductsLinks[80],
// ),
];
